# Generated by Django 2.2.13 on 2020-08-26 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_movie_production_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
