# Generated by Django 2.2.13 on 2020-08-26 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200826_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='production_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
